{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"256311","self":"https://bugreports.qt.io/rest/api/2/issue/256311","key":"QTCREATORBUG-19612","fields":{"issuetype":{"self":"https://bugreports.qt.io/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://bugreports.qt.io/secure/viewavatar?size=xsmall&avatarId=12173&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":12173},"customfield_10190":null,"timespent":null,"customfield_10030":null,"project":{"self":"https://bugreports.qt.io/rest/api/2/project/10512","id":"10512","key":"QTCREATORBUG","name":"Qt Creator","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/projectavatar?pid=10512&avatarId=10011","24x24":"https://bugreports.qt.io/secure/projectavatar?size=small&pid=10512&avatarId=10011","16x16":"https://bugreports.qt.io/secure/projectavatar?size=xsmall&pid=10512&avatarId=10011","32x32":"https://bugreports.qt.io/secure/projectavatar?size=medium&pid=10512&avatarId=10011"},"projectCategory":{"self":"https://bugreports.qt.io/rest/api/2/projectCategory/10010","id":"10010","description":"Active projects","name":"Active"}},"fixVersions":[{"self":"https://bugreports.qt.io/rest/api/2/version/17507","id":"17507","description":"4.8.1","name":"Qt Creator 4.8.1","archived":false,"released":true,"releaseDate":"2019-01-17"},{"self":"https://bugreports.qt.io/rest/api/2/version/16819","id":"16819","description":"4.9.0 Beta 1","name":"Qt Creator 4.9.0-beta1","archived":false,"released":true,"releaseDate":"2019-02-21"}],"customfield_11200":"{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@37e8fa34[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@16d628f4[overall=com.atlassian.jira.plugin.devstatus.summary.beans.PullRequestOverallBean@6b0fbeb3[stateCount=0,state=OPEN,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@40cd7491[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@30840fe6[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@1732008a[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@15ecef9[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2a9c5bbf[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@3af78a35[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3dc6ebb1[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@4a18c3f6[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@21138a9[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@431acfc[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\"cachedValue\":{\"errors\":[],\"configErrors\":[],\"summary\":{\"pullrequest\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":\"OPEN\",\"open\":true},\"byInstanceType\":{}},\"build\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"failedBuildCount\":0,\"successfulBuildCount\":0,\"unknownBuildCount\":0},\"byInstanceType\":{}},\"review\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":null,\"dueDate\":null,\"overDue\":false,\"completed\":false},\"byInstanceType\":{}},\"deployment-environment\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"topEnvironments\":[],\"showProjects\":false,\"successfulCount\":0},\"byInstanceType\":{}},\"repository\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}},\"branch\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}}}},\"isStale\":false}}","aggregatetimespent":null,"resolution":{"self":"https://bugreports.qt.io/rest/api/2/resolution/5","id":"5","description":"All attempts at reproducing this issue failed, or not enough information was available to reproduce the issue. Reading the code produces no clues as to why this behavior would occur. If more information appears later, please reopen the issue.","name":"Cannot Reproduce"},"customfield_10302":null,"resolutiondate":"2018-11-21T16:33:13.000+0000","workratio":-1,"customfield_10906":null,"customfield_10907":null,"customfield_10908":null,"customfield_10909":null,"lastViewed":"2019-02-21T12:33:19.320+0000","watches":{"self":"https://bugreports.qt.io/rest/api/2/issue/QTCREATORBUG-19612/watchers","watchCount":3,"isWatching":false},"customfield_10180":null,"customfield_10181":null,"created":"2018-01-18T12:18:08.000+0000","customfield_10183":null,"customfield_10142":"d4e79230d83f44790345115efddd0252f892e292 (qt-creator/qt-creator/4.8)","priority":{"self":"https://bugreports.qt.io/rest/api/2/priority/6","iconUrl":"https://bugreports.qt.io/images/icons/help_16.gif","name":"Not Evaluated","id":"6"},"customfield_10300":"9223372036854775807","labels":[],"customfield_10301":"9223372036854775807","timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://bugreports.qt.io/rest/api/2/version/16779","id":"16779","description":"4.5.0","name":"Qt Creator 4.5.0","archived":false,"released":true,"releaseDate":"2017-12-07"}],"issuelinks":[],"assignee":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"updated":"2018-12-12T09:50:43.000+0000","status":{"self":"https://bugreports.qt.io/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://bugreports.qt.io/images/icons/statuses/trash.png","name":"Closed","id":"6","statusCategory":{"self":"https://bugreports.qt.io/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://bugreports.qt.io/rest/api/2/component/19120","id":"19120","name":"Debugger","description":"Issues with the GDB, CDB, LLDB debugger integration"}],"timeoriginalestimate":null,"description":"It stalls on \"Setting up inferior...\" since it gets a python 2.7/2.x invoked rather than a 3.x. Qt Creator should (the very least) check the python version and write an understandable error rather than failing silently - and leaving it up to users with \"secret\" right-click and get log to try to guess the error. (Even better would be if it ensured the right python version was invoked).\r\n\r\n ","customfield_11100":null,"timetracking":{},"customfield_10600":null,"customfield_10601":null,"customfield_10800":"0|i0hjun:","attachment":[{"self":"https://bugreports.qt.io/rest/api/2/attachment/69294","id":"69294","filename":"fulllog.txt","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"created":"2018-01-18T13:47:37.000+0000","size":5252,"mimeType":"text/plain","content":"https://bugreports.qt.io/secure/attachment/69294/fulllog.txt"},{"self":"https://bugreports.qt.io/rest/api/2/attachment/77361","id":"77361","filename":"fulllog-ag.txt","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"created":"2018-10-19T10:17:53.000+0000","size":19272,"mimeType":"text/plain","content":"https://bugreports.qt.io/secure/attachment/77361/fulllog-ag.txt"},{"self":"https://bugreports.qt.io/rest/api/2/attachment/69290","id":"69290","filename":"log.txt","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"created":"2018-01-18T12:14:52.000+0000","size":1164,"mimeType":"text/plain","content":"https://bugreports.qt.io/secure/attachment/69290/log.txt"}],"aggregatetimeestimate":null,"summary":"Qt Creator fails to start debugging on Mac","creator":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"subtasks":[],"reporter":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"aggregateprogress":{"progress":0,"total":0},"customfield_10200":"9223372036854775807","customfield_10400":null,"environment":null,"customfield_10910":null,"customfield_10911":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/387161","id":"387161","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"body":"I am not the only one with this problem:\r\n\r\nhttps://forum.qt.io/topic/85010/debugger-is-not-working-on-osx-10-12-3-with-qt-5-9-and-qt-creator-4-4-1","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"created":"2018-01-18T12:21:02.000+0000","updated":"2018-01-18T12:21:02.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/387192","id":"387192","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"body":"Can you please attach a full log? \r\n\r\nIt's not that Qt Creator starts Python with LLDB, instead it starts LLDB which is linked to some version of Python, so any mismatch there looks like a broken LLDB installation.\r\n","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"created":"2018-01-18T13:19:32.000+0000","updated":"2018-01-18T13:36:09.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/387202","id":"387202","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"body":">\"It's not that Qt Creator starts Python with LLDB, instead it starts LLDB which is linked to some version of Python\"\r\n\r\nhmm, strange.\r\n\r\nMy problem is/was however instantly solved with:\r\n\r\nsudo port select --set python python36\r\n\r\nLLDB could be linked to a python36 - I have the problem that some MacPort programs require 2.x while others demand 3.x.\r\n\r\n*However*, I could however also debug with QtCreator 4.1 running on Qt 5.6.2. (The link I posted in my last comment indicates that it has to do with the Qt Version - maybe more than Qt Creator).\r\n\r\nAttached fulllog.txt","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"created":"2018-01-18T13:47:30.000+0000","updated":"2018-01-18T13:47:30.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/387203","id":"387203","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"body":"Would it at least be possible to inform about an error and show the log. The fact that it just silently fails while showing the message \"Setting up inferior...\" is pretty annoying. (I didn't even knew about a debug log before I had googled for a while ...)","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=tmartsum","name":"tmartsum","key":"tmartsum","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"Thorbjørn Lund Martsum","active":true,"timeZone":"UTC"},"created":"2018-01-18T13:50:19.000+0000","updated":"2018-01-18T13:51:02.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/387205","id":"387205","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"body":"I can only add warning once I get aware of problems, and since this \"could not happen\" (TM) I wasn't aware of it...\r\n\r\n","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"created":"2018-01-18T13:53:04.000+0000","updated":"2018-01-18T13:53:04.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/427625","id":"427625","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"body":"I am having that exact problem using Qt Creator 4.7.1 on macOS Mojave 10.14. I did `brew install python` (i.e. Python 3.7), then `cd /usr/local/bin; ln -s python3 python` and finally set `PATH=/usr/local/bin:${PATH}` for the Environment setting in Qt Kit, but to no avail. Very frustrating. :(","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"created":"2018-10-19T01:56:01.000+0000","updated":"2018-10-19T01:56:01.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/427650","id":"427650","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"body":"Alan: The python version you install and the python version used by LLDB are independent. You do not need any \"extra python\" when you use the \"system lldb\". Specifically, when things do not work, applying means that make the environment to look more like using the non-LLDB version of python, will not help.","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"created":"2018-10-19T07:07:07.000+0000","updated":"2018-10-19T07:07:07.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/427717","id":"427717","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"body":"@hjk: yes, I realised that and uninstalled it, etc. Otherwise, looking at [~tmartsum]'s log file, mine is a bit different. See attachment (fulllog-ag.txt).","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"created":"2018-10-19T10:17:46.000+0000","updated":"2018-10-19T10:17:46.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/428088","id":"428088","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"body":"Ok, FWIW, the problem I was experiencing was due to the six Python module being somehow missing. So, all I needed to do was to (re)install and, now, everything works fine.","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"created":"2018-10-22T21:49:47.000+0000","updated":"2018-10-22T21:49:47.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/428208","id":"428208","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"body":"Ok. Thanks for coming back.\r\n\r\nFor the future: Unless it's clearly the same bug I personally prefer separate reports, even at the risk that it is a true duplicate under the hood. It's easier for me to align e.g. attachments with the corresponding parts of the then-shorter and \"cleaner\" discussions.","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=hjk","name":"hjk","key":"hjk","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?avatarId=10292","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&avatarId=10292","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&avatarId=10292","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&avatarId=10292"},"displayName":"hjk","active":true,"timeZone":"Europe/Berlin"},"created":"2018-10-23T12:45:09.000+0000","updated":"2018-10-23T12:45:09.000+0000"},{"self":"https://bugreports.qt.io/rest/api/2/issue/256311/comment/428276","id":"428276","author":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"body":"[~hjk]: I appreciate that, but it's difficult to tell when you get exactly the same symptom... However, it does look like in both cases it was related to Python.","updateAuthor":{"self":"https://bugreports.qt.io/rest/api/2/user?username=agarny","name":"agarny","key":"agarny","avatarUrls":{"48x48":"https://bugreports.qt.io/secure/useravatar?ownerId=agarny&avatarId=14908","24x24":"https://bugreports.qt.io/secure/useravatar?size=small&ownerId=agarny&avatarId=14908","16x16":"https://bugreports.qt.io/secure/useravatar?size=xsmall&ownerId=agarny&avatarId=14908","32x32":"https://bugreports.qt.io/secure/useravatar?size=medium&ownerId=agarny&avatarId=14908"},"displayName":"Alan Garny","active":true,"timeZone":"Pacific/Auckland"},"created":"2018-10-23T17:34:09.000+0000","updated":"2018-10-23T17:34:09.000+0000"}],"maxResults":11,"total":11,"startAt":0},"votes":{"self":"https://bugreports.qt.io/rest/api/2/issue/QTCREATORBUG-19612/votes","votes":1,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]}}}